### ISSUE TITLE
Parsing Call Output

### ISSUE THREAD

**Issue by VertigoRay** [ppoffice/wmic.js#1]
First off, I want to thank you for building this package. You've saved me a lot of time. I've played with several other Node WMI packages and yours is the best; thus far. :beers:

I have an anomaly with the response from a call:

```
> const wmic = require('wmic-js')
undefined
> wmic({ namespace: '\\\\Root\\CIMV2\\Security\\MicrosoftVolumeEncryption' }).path('Win32_EncryptableVolume').where('DriveLetter', 'C:').call('GetKeyProtectors').then(console.log)
Promise { <pending> }
> { ReturnValue: 0,
  VolumeKeyProtectorID: [ [ NaN ], [ NaN ], [ 'CD43A336-1F07-4C28-8471-077066E80DED' ] ] }
```

If I run the same command that you're running, I get all three `VolumeKeyProtectorID`s:

```
wmic /NAMESPACE:\\Root\CIMV2\Security\MicrosoftVolumeEncryption /LOCALE:MS_409 /PRIVILEGES:ENABLE /TRACE:OFF /INTERACTIVE:OFF /FAILFAST:OFF /OUTPUT:STDOUT /APPEND:STDOUT /AGGREGATE:ON path Win32_EncryptableVolume WHERE 'DriveLetter = "C:"' CALL GetKeyProtectors 0
Executing (\\PC-Win10x64Ent\Root\CIMV2\Security\MicrosoftVolumeEncryption:Win32_EncryptableVolume.DeviceID="\\\\?\\Volume{33ee54a4-4901-4da2-b6f0-4d8acefa8764}\\")->GetKeyProtectors()
Method execution successful.
Out Parameters:
instance of __PARAMETERS
{
        ReturnValue = 0;
        VolumeKeyProtectorID = {"{85529E70-FBF4-48D7-8FBB-AB7740CD194E}", "{276C56B4-5A70-4934-A2EB-B241A934D0CB}", "{CD43A336-1F07-4C28-8471-077066E80DED}"};
};
```

To me, this looks like an issue with your output parser. I realize it gets significantly more difficult to parse the output since WMIC only `/FORMAT`s on `get`s. Any thoughts?

**Comment by VertigoRay** [comment]
Ok, the issue is here: [`extract.js:25`](https://github.com/ppoffice/wmic.js/blob/a14cc5bf0d1080d4de480bd4b2b37e84ca8325d9/lib/extract.js#L25). You're using `parseInt()` when you should probably be using `Number()` to correspond with [`extract.js:38`](https://github.com/ppoffice/wmic.js/blob/a14cc5bf0d1080d4de480bd4b2b37e84ca8325d9/lib/extract.js#L38)

```
> parseInt('85529E70-FBF4-48D7-8FBB-AB7740CD194E')
85529
> Number('85529E70-FBF4-48D7-8FBB-AB7740CD194E')
NaN
```

**Comment by VertigoRay** [comment]
```
> wmic({ namespace: '\\\\Root\\CIMV2\\Security\\MicrosoftVolumeEncryption' }).path('Win32_EncryptableVolume').where('DriveLetter', 'C:').call('GetKeyProtectors').then(console.log)
Promise { <pending> }
> { ReturnValue: 0,
  VolumeKeyProtectorID:
   [ [ '85529E70-FBF4-48D7-8FBB-AB7740CD194E' ],
     [ '276C56B4-5A70-4934-A2EB-B241A934D0CB' ],
     [ 'CD43A336-1F07-4C28-8471-077066E80DED' ] ] }
```

Confirmed, making the PR now ...

**Comment by ppoffice** [comment]
This is great! Thank you.

**Comment by VertigoRay** [comment]
Thanks for accepting this so fast! ☕️ 

I'm sure it was just an oversite, but NPM still has:

![image](https://user-images.githubusercontent.com/792482/29079131-f350f7a6-7c21-11e7-8312-de573fbd45b9.png)

Can you publish a new release and it published to NPM, please?

**Comment by ppoffice** [comment]
Sure. I'm on it.

**Comment by ppoffice** [comment]
@VertigoRay It's done.
