### ISSUE TITLE
I keep on getting errors, /bin/sh wmic: not found

### ISSUE THREAD

**Issue by djloot** [ppoffice/wmic.js#3]
Does this require a binary 'wmic' to be installed on the machine? if so, on what platform?
I'm trying to do wmi queries from a raspberry pi to a win7 machine. I have it working but thought it will be easier for me to do it via node.js. Am I barking up the wrong tree here?

**Comment by ppoffice** [comment]
@djloot This one is for windows. I'm not sure if there are any WMIC clients for Linux, but you definitely need to install one if there is.

**Comment by djloot** [comment]
thank you. That was the issue. There is a wmic client for linux and I have it working, just has a different syntax and may not do as much.  Thanks for the response. I'll see if I can get it working
